 '(TeX-PDF-mode t)
 '(TeX-output-view-style (quote (("^dvi$" ("^landscape$" "^pstricks$\\|^pst-\\|^psfrag$") "%(o?)dvips -t landscape %d -o && gv %f") ("^dvi$" "^pstricks$\\|^pst-\\|^psfrag$" "%(o?)dvips %d -o && gv %f") ("^dvi$" ("^a4\\(?:dutch\\|paper\\|wide\\)\\|sem-a4$" "^landscape$") "%(o?)xdvi %dS -paper a4r -s 0 %d") ("^dvi$" "^a4\\(?:dutch\\|paper\\|wide\\)\\|sem-a4$" "%(o?)xdvi %dS -paper a4 %d") ("^dvi$" ("^a5\\(?:comb\\|paper\\)$" "^landscape$") "%(o?)xdvi %dS -paper a5r -s 0 %d") ("^dvi$" "^a5\\(?:comb\\|paper\\)$" "%(o?)xdvi %dS -paper a5 %d") ("^dvi$" "^b5paper$" "%(o?)xdvi %dS -paper b5 %d") ("^dvi$" "^letterpaper$" "%(o?)xdvi %dS -paper us %d") ("^dvi$" "^legalpaper$" "%(o?)xdvi %dS -paper legal %d") ("^dvi$" "^executivepaper$" "%(o?)xdvi %dS -paper 7.25x10.5in %d") ("^dvi$" "." "%(o?)xdvi %dS %d") ("^pdf$" "." "evince %o") ("^html?$" "." "netscape %o"))))
 '(bookmark-save-flag 0)
 '(c-basic-offset 2)
 '(calendar-week-start-day 1)
 '(case-fold-search t)
 '(case-replace t)
 '(column-number-mode t)
 '(compilation-auto-jump-to-first-error t)
 '(compilation-debug nil t)
 '(compilation-environment nil t)
 '(compilation-first-column 1 t)
 '(compilation-process-setup-function nil t)
 '(compilation-scroll-output t)
 '(compilation-skip-to-next-location t t)
 '(compilation-window-height 30)
 '(current-language-environment "UTF-8")
 '(dabbrev-case-replace nil)
 '(default-input-method "rfc1345")
 '(emacsw32-eol-check-new-files t)
 '(emacsw32-max-frames t)
 '(emacsw32-mode nil)
 '(emacsw32-style-frame-title t)
 '(gdb-create-source-file-list nil)
 '(global-auto-revert-mode t)
 '(global-font-lock-mode t nil (font-lock))
 '(graphviz-dot-auto-indent-on-braces t)
 '(graphviz-dot-view-edit-command nil)
 '(grep-files-aliases (quote (("asm" . "*.[sS]") ("c" . "*.c") ("cc" . "*.cc *.cxx *.cpp *.C *.CC *.c++") ("ch" . "*.[ch]") ("el" . "*.el") ("h" . "*.h") ("l" . "[Cc]hange[Ll]og*") ("m" . "[Mm]akefile*") ("tex" . "*.tex") ("texi" . "*.texi") ("cch" . "*.c *.cc *.h *.[ch]xx *.[ch]pp *.[CH] *.CC *.HH *.[ch]++"))))
 '(icicle-Completions-window-max-height 40)
 '(icicle-anything-transform-candidates-flag t)
 '(icicle-download-dir "~/emacs/icicles")
 '(icicle-list-join-string "
")
 '(icicle-reminder-prompt-flag 0)
 '(indent-region-mode t)
 '(menu-bar-mode t)
 '(nxhtml-global-minor-mode t)
 '(nxhtml-global-validation-header-mode t)
 '(nxhtml-load t)
 '(pop-up-windows t)
 '(ps-paper-type (quote a4))
 '(recentf-mode t)
 '(show-paren-mode t nil (paren))
 '(split-width-threshold nil)
 '(tooltip-mode nil)
 '(tool-bar-mode nil)
 '(uniquify-buffer-name-style (quote reverse) nil (uniquify))
 '(use-file-dialog nil)
 '(make-backup-files nil)
 '(ns-command-modifier (quote meta)))



(custom-set-faces
'(default ((t (:stipple nil :background "#ffffff" :foreground "#000000" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 116 :width normal :foundry "unknown" :family "DejaVu Sans Mono")))))
  